### ISSUE TITLE
Library Catalog Breakpoints Need Adjusted

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucd-lib-elements#8]
I consider this a critical usability issue, so let's get it done asap, please!

## Maintain Space Between Options
Deanna helped bring to my attention that there are some is some issues with the breakpoints for the links under the search field on the Library Catalog + Articles section.

She identified that on smaller screens, the ‘Library Catalog only’ and ‘Advanced Search’ below the search box are very close together, making them difficult to differentiate. Deanna sent this screenshot as an example:

![image001](https://user-images.githubusercontent.com/17831969/55365347-0dd05f80-5499-11e9-8e96-60fc5c9fbdfa.png)

To avoid this, **there should never be less than 40 px** between the end of "Library catalog only" and beginning of "Advanced search." This will make sure it remains readable. 

## Treat Links as Units
In addition, I noticed that we're getting weird breaks like these:

![Screen Shot 2019-04-01 at 4 15 15 PM](https://user-images.githubusercontent.com/17831969/55365430-69025200-5499-11e9-9ebe-4e8e6dac5731.png)

![Screen Shot 2019-04-01 at 4 15 29 PM](https://user-images.githubusercontent.com/17831969/55365437-6bfd4280-5499-11e9-8f49-7bd6e3e8037b.png)

![Screen Shot 2019-04-01 at 4 20 56 PM](https://user-images.githubusercontent.com/17831969/55365656-2ee58000-549a-11e9-9eda-2de3790d8be8.png)

![Screen Shot 2019-04-01 at 4 18 55 PM](https://user-images.githubusercontent.com/17831969/55365570-ddd58c00-5499-11e9-9d94-5cb6aa22a598.png)

This is... not good. It is, in fact, unusably bad. Each of these links need to be **treated as a complete unit** to maintain readability.

## Examples of GOOD Breaks

![Screen Shot 2019-04-01 at 4 17 40 PM](https://user-images.githubusercontent.com/17831969/55365549-cac2bc00-5499-11e9-8a9a-87d3a993c445.png)

![Screen Shot 2019-04-01 at 4 21 44 PM](https://user-images.githubusercontent.com/17831969/55365823-d6fb4900-549a-11e9-9831-2406d60b6d4b.png)

![Screen Shot 2019-04-01 at 4 34 21 PM](https://user-images.githubusercontent.com/17831969/55366091-15ddce80-549c-11e9-9655-767cc396c7f3.png)

It looks like this issue also affects the "Subject and Course Guides" section of the search widget. 

The "All UC Libraries (Melvyl)" section looks like it breaks okay, but maybe double check to be sure.

**Comment by spelkey-ucd** [comment]
fix is on rc.

**Comment by wrenaria** [comment]
@spelkey-ucd This looks great. Thanks!
